<?php

namespace proyecto\PersonasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * pacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pacienteRepository extends EntityRepository
{
    public function buscarPorNombreYApellido($NombreYApellido){
        $em= $this->getEntityManager();
                
        $query= $em->createQuery('SELECT p FROM ProyectoPersonasBundle:paciente P WHERE P.NombreYApellido LIKE:NombreYApellido')->setParameter('NombreYApellido' ,$NombreYApellido);
        
        return $query->getResult();

    }
            
}