<?php

namespace proyecto\PersonasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tratamientoRepository extends EntityRepository
{
}
